import { NavItem } from "@/ui";
import { PermissionRule } from "@/shared/helpers/permissions";
import { NavigationIconKey } from "@/ui/components/navigation/IconRegistry";

export interface NavigationConfig extends NavItem {
  id?: string;
  label: string;
  href: string;
  icon?: NavigationIconKey;
  description?: string;
  tagText?: string;
  showInLauncher?: boolean;
  showInSidebar?: boolean;
  showInTabs?: boolean;
  requiredPermissions?: PermissionRule;
  highlight?: boolean;
  mobile?: {
    priority?: number;
  };
  entryStrategy?: "firstAllowedChild" | "self";
  routes?: NavigationConfig[];
}

export const itemsNavigation: NavigationConfig[] = [
  {
    id: "quick-operations",
    label: "Operaciones Rápidas",
    href: "quick-operations",
    action: "quick-operations",
    subject: "home",
    icon: "quick-operations",
    highlight: true,
    hiddenInSidebar: true,
    mobile: { priority: 1 },
    entryStrategy: "self",
    showInLauncher: true,
    description: "Gestón unificada de secretaría, operaciones y flujo de caja.",
    tagText: "Secretaría",
    requiredPermissions: { anyOf: ["READ_PERSONS"] },
    routes: [
      {
        id: "quick-ops-person",
        label: "Ficha",
        href: "/admin/quick-operations/[personId]",
        action: "quick-operations",
        subject: "home",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_PERSONS"] },
      },
      {
        id: "quick-ops-dashboard",
        label: "Dashboard",
        href: "/admin/quick-operations/dashboard",
        action: "quick-operations",
        subject: "home",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_DASHBOARD", "READ_TRANSACTIONS"] },
      },
      {
        id: "quick-ops-cash",
        label: "Flujo de Caja",
        href: "/admin/quick-operations/cash-flow",
        action: "quick-operations",
        subject: "home",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_TRANSACTIONS", "READ_CASH_FLOW"] },
      },
      {
        id: "quick-ops-reports",
        label: "Reportes",
        href: "/admin/quick-operations/reports",
        action: "quick-operations",
        subject: "home",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_REPORTS", "READ_TRANSACTIONS"] },
      },
    ],
  },
  {
    id: "dashboard",
    label: "Inicio",
    href: "dashboard",
    action: "dashboard",
    subject: "home",
    icon: "dashboard",
    mobile: { priority: 10 },
    showInLauncher: true,
    description:
      "Gestiona la configuración, estructura y operación de la organización deportiva desde un único panel centralizado.",
    tagText: "Panel Administrativo",
    requiredPermissions: {
      anyOf: [
        "READ_DASHBOARD",
        "READ_DISCIPLINES",
        "READ_LOCATIONS",
        "READ_CATEGORIES",
        "READ_SEASONS",
        "READ_CLUBS",
        "READ_USERS",
        "READ_ROLES",
      ],
    },
  },
  {
    label: "Disciplinas",
    href: "disciplines",
    action: "disciplines",
    subject: "DISCIPLINES",
    icon: "disciplines",
    requiredPermissions: { anyOf: ["READ_DISCIPLINES"] },
  },
  {
    label: "Instalaciones",
    href: "locations",
    action: "locations",
    subject: "LOCATIONS",
    icon: "locations",
    requiredPermissions: { anyOf: ["READ_LOCATIONS"] },
  },
  {
    label: "Categorias",
    href: "categories",
    action: "categories",
    subject: "CATEGORIES",
    icon: "categories",
    requiredPermissions: { anyOf: ["READ_CATEGORIES"] },
  },
  {
    label: "Temporadas",
    href: "seasons",
    action: "seasons",
    subject: "SEASONS",
    icon: "seasons",
    requiredPermissions: { anyOf: ["READ_SEASONS"] },
  },
  {
    label: "Clubes",
    href: "clubs",
    action: "clubs",
    subject: "CLUBS",
    icon: "clubs",
    requiredPermissions: { anyOf: ["READ_CLUBS"] },
  },
  {
    label: "Equipos",
    href: "teams",
    action: "teams",
    subject: "TEAMS",
    icon: "teams",
    mobile: { priority: 7 },
    requiredPermissions: { anyOf: ["READ_TEAMS"] },
  },
  {
    label: "Jugadores",
    href: "players",
    action: "players",
    subject: "PLAYERS",
    icon: "players",
    requiredPermissions: { anyOf: ["READ_PLAYERS"] },
  },
  {
    id: "memberships",
    label: "Membresías",
    href: "memberships",
    action: "memberships",
    subject: ["PLAYER_MEMBERSHIPS", "STUDENT_MEMBERSHIPS"],
    icon: "memberships",
    mobile: { priority: 9 },
    entryStrategy: "firstAllowedChild",
    routes: [
      {
        id: "memberships-players",
        label: "Jugadores",
        href: "/admin/memberships/player-memberships",
        action: "memberships",
        subject: "PLAYER_MEMBERSHIPS",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_PLAYER_MEMBERSHIPS"] },
      },
      {
        id: "memberships-students",
        label: "Estudiantes",
        href: "/admin/memberships/student-memberships",
        action: "memberships",
        subject: "STUDENT_MEMBERSHIPS",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_STUDENT_MEMBERSHIPS"] },
      },
    ],
  },
  {
    label: "Escuelas",
    href: "schools",
    action: "schools",
    subject: "SCHOOLS",
    icon: "schools",
    requiredPermissions: { anyOf: ["READ_SCHOOLS"] },
  },
  {
    label: "Cursos",
    href: "courses",
    action: "courses",
    subject: "COURSES",
    icon: "courses",
    mobile: { priority: 8 },
    requiredPermissions: { anyOf: ["READ_COURSES"] },
  },
  {
    label: "Estudiantes",
    href: "students",
    action: "students",
    subject: "STUDENTS",
    icon: "students",
    requiredPermissions: { anyOf: ["READ_STUDENTS"] },
  },
  {
    id: "accounting",
    label: "Contabilidad",
    href: "accounting",
    action: "accounting",
    subject: ["ACCOUNT_CHARGES", "ACCOUNT_CATEGORIES"],
    icon: "accounting",
    entryStrategy: "firstAllowedChild",
    routes: [
      {
        id: "accounting-dashboard",
        label: "Dashboard",
        href: "/admin/accounting/dashboard",
        action: "accounting",
        subject: "ACCOUNT_CHARGES",
        showInTabs: true,
        requiredPermissions: {
          anyOf: ["READ_ACCOUNT_CHARGES", "READ_TRANSACTIONS"],
        },
      },
      {
        id: "accounting-cash-flow",
        label: "Flujo de Caja",
        href: "/admin/accounting/cash-flow",
        action: "accounting",
        subject: "ACCOUNT_CHARGES",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_TRANSACTIONS", "READ_CASH_FLOW"] },
      },
      {
        id: "accounting-accounts",
        label: "Cuentas",
        href: "/admin/accounting/accounts",
        action: "accounting",
        subject: "FINANCIAL_ACCOUNTS",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_FINANCIAL_ACCOUNTS"] },
      },
      {
        id: "accounting-transfers",
        label: "Transferencias",
        href: "/admin/accounting/transfers",
        action: "accounting",
        subject: "INTERNAL_TRANSFERS",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_INTERNAL_TRANSFERS"] },
      },
      {
        id: "accounting-receivables",
        label: "Cuentas por Cobrar",
        href: "/admin/accounting/receivables",
        action: "accounting",
        subject: "ACCOUNT_CHARGES",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_ACCOUNT_CHARGES"] },
      },
      {
        id: "accounting-categories",
        label: "Categorías",
        href: "/admin/accounting/categories",
        action: "accounting",
        subject: "ACCOUNT_CATEGORIES",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_ACCOUNT_CATEGORIES"] },
      },
      {
        id: "accounting-payables",
        label: "Cuentas por Pagar",
        href: "/admin/accounting/payables",
        action: "accounting",
        subject: "ACCOUNT_CHARGES",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_ACCOUNT_CHARGES"] },
      },
      {
        id: "accounting-reports",
        label: "Reportes",
        href: "/admin/accounting/reports",
        action: "accounting",
        subject: "REPORTS",
        showInTabs: true,
        requiredPermissions: { anyOf: ["READ_REPORTS"] },
      },
    ],
  },
  {
    id: "members",
    label: "Personas",
    href: "members",
    action: "members",
    subject: "PERSONS",
    icon: "players",
    showInLauncher: false,
    requiredPermissions: { anyOf: ["READ_PERSONS"] },
  },
  {
    label: "Turnos",
    href: "shifts",
    action: "shifts",
    subject: "home",
    icon: "shifts",
    requiredPermissions: { anyOf: ["READ_SHIFTS"] },
  },
  {
    id: "users",
    label: "Usuarios",
    href: "users",
    action: "users",
    subject: "USERS",
    icon: "users",
    showInLauncher: false,
    requiredPermissions: { anyOf: ["READ_USERS"] },
  },
  {
    id: "roles",
    label: "Roles y Permisos",
    href: "roles",
    action: "roles",
    subject: "ROLES",
    icon: "roles",
    showInLauncher: false,
    requiredPermissions: { anyOf: ["READ_ROLES"] },
  },
  {
    id: "calendar",
    label: "Calendario Institucional",
    href: "calendar",
    action: "calendar",
    subject: "home",
    icon: "calendar",
    hiddenInSidebar: true,
    showInLauncher: true,
    description:
      "Gestione y visualice todos los eventos, entrenamientos y partidos del club.",
    tagText: "Organización",
    requiredPermissions: {
      anyOf: ["READ_SCHEDULES", "READ_MATCHES", "READ_SESSIONS"],
    },
  },
  {
    id: "web",
    label: "Administración Web",
    href: "web",
    action: "web",
    subject: "home",
    icon: "web",
    hiddenInSidebar: true,
    showInLauncher: true,
    description:
      "Gestiona las noticias, publicaciones, anuncios, historia e información de 'Nosotros' en el portal web del club.",
    tagText: "CMS y Portales",
    requiredPermissions: {
      anyOf: ["READ_BANNERS", "READ_NEWS", "READ_PROMOTIONS"],
    },
  },
  {
    id: "portal",
    label: "Portal Web",
    href: "/",
    action: "web",
    subject: "home",
    icon: "web",
    showInLauncher: true,
    description: "Ir a la página principal del portal público.",
    tagText: "Público",
  },
];

export const itemsWebNavigation: NavigationConfig[] = [
  {
    id: "web-home",
    label: "Inicio",
    href: "home",
    action: "web_home",
    subject: "home",
    icon: "dashboard",
  },
  {
    id: "web-hero-banners",
    label: "Hero Banners",
    href: "hero-banners",
    action: "web_banners",
    subject: "home",
    icon: "categories",
    requiredPermissions: { anyOf: ["READ_BANNERS"] },
  },
  {
    id: "web-home-disciplines",
    label: "Equipos/Escuela",
    href: "home-disciplines",
    action: "web_banners",
    subject: "home",
    icon: "disciplines",
    requiredPermissions: { anyOf: ["READ_BANNERS"] },
  },
  {
    id: "web-news",
    label: "Noticias",
    href: "news",
    action: "web_news",
    subject: "home",
    icon: "news",
    requiredPermissions: { anyOf: ["READ_NEWS"] },
  },
  {
    id: "web-promotions",
    label: "Promociones",
    href: "promotions",
    action: "web_banners",
    subject: "home",
    icon: "categories",
    requiredPermissions: { anyOf: ["READ_PROMOTIONS"] },
  },
  // enlace al crud de la historia de la institution
  {
    id: "web-institution-history",
    label: "Historia",
    href: "institution-history",
    action: "web_banners",
    subject: "home",
    icon: "calendar", // using calendar as an icon, or dashboard. The user said: "Elegir icon existente coherente con: Historia / Timeline / Institución". I'll check available icons later.
    requiredPermissions: { anyOf: ["READ_INSTITUTION_HISTORY"] },
  },
];
