import { NavItem } from "@/ui";
import {
  ArrowDataTransferHorizontalIcon,
  BookOpen01Icon,
  Building03FreeIcons,
  Building03Icon,
  Calendar03Icon,
  Calendar04Icon,
  CheckmarkSquare03Icon,
  DashboardSquare02Icon,
  DistributeVerticalBottomIcon,
  Flag03Icon,
  IdentityCardIcon,
  Layers01Icon,
  Mortarboard02Icon,
  Structure04FreeIcons,
  Structure04Icon,
  StudentIcon,
  TaskDone01Icon,
  UserGroupIcon,
  UserIcon,
  UserMultipleIcon,
  Time02Icon,
  Invoice01Icon,
} from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";

export const itemsNavigation: NavItem[] = [
  {
    label: "Dashboard",
    href: "dashboard",
    action: "dashboard",
    subject: "home",
    icon: <HugeiconsIcon icon={DashboardSquare02Icon} size={20} />,
    mobile: { priority: 10 },
  },
  {
    label: "Disciplinas",
    href: "disciplines",
    action: "disciplines",
    subject: "DISCIPLINES",
    icon: <HugeiconsIcon icon={Structure04FreeIcons} size={20} />,
  },
  {
    label: "Instalaciones",
    href: "locations",
    action: "locations",
    subject: "LOCATIONS",
    icon: <HugeiconsIcon icon={Building03Icon} size={20} />,
  },
  {
    label: "Categorias",
    href: "categories",
    action: "categories",
    subject: "CATEGORIES",
    icon: <HugeiconsIcon icon={Layers01Icon} size={20} />,
  },
  {
    label: "Temporadas",
    href: "seasons",
    action: "seasons",
    subject: "SEASONS",
    icon: <HugeiconsIcon icon={Calendar04Icon} size={20} />,
  },
  {
    label: "Clubes",
    href: "clubs",
    action: "clubs",
    subject: "CLUBS",
    icon: <HugeiconsIcon icon={Flag03Icon} size={20} />,
  },
  {
    label: "Equipos",
    href: "teams",
    action: "teams",
    subject: "TEAMS",
    icon: <HugeiconsIcon icon={UserGroupIcon} size={20} />,
    mobile: { priority: 7 },
  },
  {
    label: "Jugadores",
    href: "players",
    action: "players",
    subject: "PLAYERS",
    icon: <HugeiconsIcon icon={UserMultipleIcon} size={20} />,
  },
  {
    label: "Membresías",
    href: "memberships",
    action: "memberships",
    subject: ["PLAYER_MEMBERSHIPS", "STUDENT_MEMBERSHIPS"],
    icon: <HugeiconsIcon icon={IdentityCardIcon} size={20} />,
    mobile: { priority: 9 },
  },
  {
    label: "Escuelas",
    href: "schools",
    action: "schools",
    subject: "SCHOOLS",
    icon: <HugeiconsIcon icon={Mortarboard02Icon} size={20} />,
    mobile: { priority: 8 },
  },
  {
    label: "Cursos",
    href: "courses",
    action: "courses",
    subject: "COURSES",
    icon: <HugeiconsIcon icon={BookOpen01Icon} size={20} />,
  },
  {
    label: "Estudiantes",
    href: "students",
    action: "students",
    subject: "STUDENTS",
    icon: <HugeiconsIcon icon={StudentIcon} size={20} />,
  },
  {
    label: "Contabilidad",
    href: "accounting",
    action: "accounting",
    subject: ["ACCOUNT_CHARGES", "ACCOUNT_CATEGORIES"],
    icon: <HugeiconsIcon icon={Invoice01Icon} size={20} />,
  },
  {
    label: "Asistencia",
    href: "/attendance",
    action: "attendance",
    subject: "home",
    icon: <HugeiconsIcon icon={TaskDone01Icon} size={20} />,
  },
  {
    label: "Turnos",
    href: "shifts",
    action: "shifts",
    subject: "home",
    icon: <HugeiconsIcon icon={Time02Icon} size={20} />,
  },
];
