import { NavItem } from "@/ui";
import {
  ArrowDataTransferHorizontalIcon,
  BookOpen01Icon,
  Building03FreeIcons,
  Building03Icon,
  Calendar03Icon,
  Calendar04Icon,
  CheckmarkSquare03Icon,
  DashboardSquare02Icon,
  DistributeVerticalBottomIcon,
  Flag03Icon,
  IdentityCardIcon,
  Layers01Icon,
  Mortarboard02Icon,
  Structure04FreeIcons,
  Structure04Icon,
  StudentIcon,
  TaskDone01Icon,
  UserGroupIcon,
  UserIcon,
  UserMultipleIcon,
} from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";

export const itemsNavigation: NavItem[] = [
  {
    label: "Dashboard",
    href: "dashboard",
    action: "dashboard",
    subject: "home",
    icon: <HugeiconsIcon icon={DashboardSquare02Icon} size={20} />,
  },
  {
    label: "Disciplinas",
    href: "disciplines",
    action: "disciplines",
    subject: "home",
    icon: <HugeiconsIcon icon={Structure04FreeIcons} size={20} />,
  },
  {
    label: "Instalaciones",
    href: "locations",
    action: "locations",
    subject: "home",
    icon: <HugeiconsIcon icon={Building03Icon} size={20} />,
  },
  {
    label: "Categorias",
    href: "categories",
    action: "categories",
    subject: "home",
    icon: <HugeiconsIcon icon={Layers01Icon} size={20} />,
  },
  {
    label: "Temporadas",
    href: "seasons",
    action: "seasons",
    subject: "home",
    icon: <HugeiconsIcon icon={Calendar04Icon} size={20} />,
  },
  {
    label: "Clubes",
    href: "clubs",
    action: "clubs",
    subject: "home",
    icon: <HugeiconsIcon icon={Flag03Icon} size={20} />,
  },
  {
    label: "Equipos",
    href: "teams",
    action: "teams",
    subject: "home",
    icon: <HugeiconsIcon icon={UserGroupIcon} size={20} />,
  },
  {
    label: "Jugadores",
    href: "players",
    action: "players",
    subject: "home",
    icon: <HugeiconsIcon icon={UserMultipleIcon} size={20} />,
  },
  {
    label: "Escuelas",
    href: "schools",
    action: "schools",
    subject: "home",
    icon: <HugeiconsIcon icon={Mortarboard02Icon} size={20} />,
  },
  {
    label: "Cursos",
    href: "courses",
    action: "courses",
    subject: "home",
    icon: <HugeiconsIcon icon={BookOpen01Icon} size={20} />,
  },
  {
    label: "Estudiantes",
    href: "students",
    action: "students",
    subject: "home",
    icon: <HugeiconsIcon icon={StudentIcon} size={20} />,
  },
  {
    label: "Asistencia",
    href: "/attendance",
    action: "attendance",
    subject: "home",
    icon: <HugeiconsIcon icon={TaskDone01Icon} size={20} />,
  },
];
